name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
        
    - name: Copy JAR to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key 
        scp -o StrictHostKeyChecking=no -i private_key target/*.jar ${USER}@${HOST}:~/app.jar
    
    - name: ssh to ec2
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        script: |           
          PIDS=$(pgrep -f "java -jar -Dspring.profiles.active=prod app.jar")
          if [ $(echo "$PIDS" | wc -l) -gt 1 ]; then
              kill $(echo "$PIDS" | head -n 1) || true
          fi
          sudo nohup java -jar -Dspring.profiles.active=prod app.jar > app.log 2>&1 &
     
          
